### ouverture des fichiers et jointures

In [5]:
import geopandas as gpd
import matplotlib.pyplot as plt
import rasterio
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from pathlib import Path
from fonction import *

In [6]:
fp = Path("data") / "raw" / "communes" / "ADE_4-0_GPKG_WGS84G_FRA-ED2025-11-20.gpkg"
if not fp.exists():
	raise FileNotFoundError(f"File not found: {fp.resolve()}")
communes = gpd.read_file(fp, layer='commune')

In [7]:
display(communes.head())

,cleabs,nom_officiel,nom_officiel_en_majuscules,statut,code_insee,population,date_du_recensement,organisme_recenseur,code_insee_du_canton,code_insee_de_l_arrondissement,code_insee_du_departement,code_insee_de_la_region,codes_siren_des_epci,code_siren,code_postal,superficie_cadastrale,geometry
0,COMMUNE_0000000000001001,L'Abergement-Clémenciat,L'ABERGEMENT-CLEMENCIAT,Commune simple,01001,859,2022-01-01,INSEE,0108,012,01,84,200069193,210100012,01400,1590,"MULTIPOLYGON (((4.95841 46.15327, 4.95812 46.1..."
1,COMMUNE_0000000000001002,L'Abergement-de-Varey,L'ABERGEMENT-DE-VAREY,Commune simple,01002,273,2022-01-01,INSEE,0101,011,01,84,240100883,210100020,01640,920,"MULTIPOLYGON (((5.4302 45.98277, 5.43012 45.98..."
2,COMMUNE_0000000000001004,Ambérieu-en-Bugey,AMBERIEU-EN-BUGEY,Commune simple,01004,15554,2022-01-01,INSEE,0101,011,01,84,240100883,210100046,01500,2460,"MULTIPOLYGON (((5.40882 45.94206, 5.4085 45.94..."
3,COMMUNE_0000000000001005,Ambérieux-en-Dombes,AMBERIEUX-EN-DOMBES,Commune simple,01005,1917,2022-01-01,INSEE,0122,012,01,84,200042497,210100053,01330,1590,"MULTIPOLYGON (((4.94298 45.97962, 4.94257 45.9..."
4,COMMUNE_0000000000001006,Ambléon,AMBLEON,Commune simple,01006,114,2022-01-01,INSEE,0104,011,01,84,200040350,210100061,01300,590,"MULTIPOLYGON (((5.57083 45.75338, 5.57219 45.7..."

In [8]:
fp = Path("data") / "intermediate" / "datagouv" / "swimonthly_combined_1958to2025.gpkg"
if not fp.exists():
	raise FileNotFoundError(f"File not found: {fp.resolve()}")
swi_monthly = gpd.read_file(fp)

In [9]:
swi_monthly['DATE'] = pd.to_datetime(swi_monthly['DATE']) - pd.offsets.MonthBegin(1)
display(swi_monthly.head())

,DATE,LAMBX,LAMBY,PRENEI,PRELIQ,T,FF,Q,DLI,SSI,...,HTEURNEIGE,HTEURNEIGE6,HTEURNEIGEX,SNOW_FRAC,ECOULEMENT,WG_RACINE,WGI_RACINE,TINF_H,TSUP_H,geometry
0,1958-08-01,600,24010,0.0,101.1,16.183871,3.735484,10.297871,104077.3,31484.2,...,0.0,0.0,0.0,0.0,0.0,0.234903,0.0,10.3,21.4,POINT (60000 2401000)
1,1958-08-01,760,23610,0.0,85.0,16.277419,4.748387,10.441677,103165.5,31824.6,...,0.0,0.0,0.0,0.0,0.0,0.174645,0.0,11.5,21.5,POINT (76000 2361000)
2,1958-08-01,760,23930,0.0,84.1,16.400000,4.719355,10.511032,103705.2,31824.6,...,0.0,0.0,0.0,0.0,0.0,0.226355,0.0,11.6,21.8,POINT (76000 2393000)
3,1958-08-01,760,24010,0.0,103.3,15.819355,3.800000,10.094516,102541.1,31493.2,...,0.0,0.0,0.0,0.0,0.0,0.220677,0.0,10.2,20.6,POINT (76000 2401000)
4,1958-08-01,760,24090,0.0,102.4,15.958065,3.764516,10.168677,103106.1,31489.5,...,0.0,0.0,0.0,0.0,0.0,0.217355,0.0,10.2,20.9,POINT (76000 2409000)

In [10]:
fp = Path("data") / "intermediate" / "meteo_france" / "meteo_france_combined.gpkg"
if not fp.exists():
    raise FileNotFoundError(f"File not found: {fp.resolve()}")
meteo_france = gpd.read_file(fp)

In [11]:
display(meteo_france.head())

   NUMERO   LAMBX    LAMBY       DATE SWI_UNIF_MENS                geometry
0       2  641374  7106309 1960-01-01         0,863  POINT (641374 7106309)
1       2  641374  7106309 1960-02-01         0,876  POINT (641374 7106309)
2       2  641374  7106309 1960-03-01         0,856  POINT (641374 7106309)
3       2  641374  7106309 1960-04-01         0,757  POINT (641374 7106309)
4       2  641374  7106309 1960-05-01         0,673  POINT (641374 7106309)

In [12]:
fp = Path("data") / "intermediate" / "argile" / "argile.gpkg"
if not fp.exists():
    raise FileNotFoundError(f"File not found: {fp.resolve()}")
argile = gpd.read_file(fp)

In [13]:
argile.crs

<Projected CRS: EPSG:3857>
Name: WGS 84 / Pseudo-Mercator
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: World between 85.06°S and 85.06°N.
- bounds: (-180.0, -85.06, 180.0, 85.06)
Coordinate Operation:
- name: Popular Visualisation Pseudo-Mercator
- method: Popular Visualisation Pseudo Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

### jointure des bases

In [ ]:
# Reproject swi_monthly to match the CRS of argile
print(swi_monthly.crs)
cols_argile = ["geometry", "ALEA", "NIVEAU", "DPT"]
argile=argile.to_crs(swi_monthly.crs)

swi_monthly_argile = gpd.sjoin(
    swi_monthly,
    argile[cols_argile],
    how="left",
    predicate="intersects"  # ou "within", l’un ou l’autre pour des points dans des polygones
)

EPSG:27572

In [23]:
swi_monthly_argile

,DATE,LAMBX,LAMBY,PRENEI,PRELIQ,T,FF,Q,DLI,SSI,...,ECOULEMENT,WG_RACINE,WGI_RACINE,TINF_H,TSUP_H,geometry,index_right,ALEA,NIVEAU,DPT
0,1958-08-01,600,24010,0.0,101.1,16.183871,3.735484,10.297871,104077.3,31484.2,...,0.0,0.234903,0.0,10.3,21.4,POINT (60000 2401000),NaN,NaN,NaN,NaN
1,1958-08-01,760,23610,0.0,85.0,16.277419,4.748387,10.441677,103165.5,31824.6,...,0.0,0.174645,0.0,11.5,21.5,POINT (76000 2361000),NaN,NaN,NaN,NaN
2,1958-08-01,760,23930,0.0,84.1,16.400000,4.719355,10.511032,103705.2,31824.6,...,0.0,0.226355,0.0,11.6,21.8,POINT (76000 2393000),NaN,NaN,NaN,NaN
3,1958-08-01,760,24010,0.0,103.3,15.819355,3.800000,10.094516,102541.1,31493.2,...,0.0,0.220677,0.0,10.2,20.6,POINT (76000 2401000),NaN,NaN,NaN,NaN
4,1958-08-01,760,24090,0.0,102.4,15.958065,3.764516,10.168677,103106.1,31489.5,...,0.0,0.217355,0.0,10.2,20.9,POINT (76000 2409000),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982859,2025-10-01,11960,17050,0.0,44.5,18.122581,2.538710,8.597774,91740.2,33351.6,...,0.0,0.190774,0.0,12.5,25.8,POINT (1196000 1705000),1180349.0,Faible,1.0,202.0
7982860,2025-10-01,11960,17130,0.0,27.8,16.987097,2.683871,7.945290,92372.0,33203.6,...,0.0,0.194065,0.0,9.3,25.8,POINT (1196000 1713000),1180449.0,Moyen,2.0,202.0
7982861,2025-10-01,11960,17210,0.0,27.8,16.967742,2.683871,7.937194,92353.8,33201.1,...,0.0,0.186806,0.0,9.3,25.8,POINT (1196000 1721000),1180520.0,Faible,1.0,202.0
7982862,2025-10-01,11960,17290,0.0,27.8,16.967742,2.683871,7.937194,92353.8,33201.1,...,0.0,0.204161,0.0,9.3,25.8,POINT (1196000 1729000),NaN,NaN,NaN,NaN
7982863,2025-10-01,11960,17450,0.0,27.7,17.100000,2.700000,7.990484,92475.1,33216.9,...,0.0,0.205387,0.0,9.5,25.8,POINT (1196000 1745000),NaN,NaN,NaN,NaN

In [24]:

# Perform a spatial join using the nearest method
swi_monthly_argile_nearest = gpd.sjoin_nearest(
    swi_monthly,
    argile[cols_argile],
    how="left",
    distance_col="dist_to_argile"
)

In [25]:
swi_monthly_argile_nearest

,DATE,LAMBX,LAMBY,PRENEI,PRELIQ,T,FF,Q,DLI,SSI,...,WG_RACINE,WGI_RACINE,TINF_H,TSUP_H,geometry,index_right,ALEA,NIVEAU,DPT,dist_to_argile
0,1958-08-01,600,24010,0.0,101.1,16.183871,3.735484,10.297871,104077.3,31484.2,...,0.234903,0.0,10.3,21.4,POINT (60000 2401000),27,Faible,1.0,29,2063.770829
1,1958-08-01,760,23610,0.0,85.0,16.277419,4.748387,10.441677,103165.5,31824.6,...,0.174645,0.0,11.5,21.5,POINT (76000 2361000),331,Faible,1.0,29,683.329171
2,1958-08-01,760,23930,0.0,84.1,16.400000,4.719355,10.511032,103705.2,31824.6,...,0.226355,0.0,11.6,21.8,POINT (76000 2393000),156,Faible,1.0,29,1021.905694
3,1958-08-01,760,24010,0.0,103.3,15.819355,3.800000,10.094516,102541.1,31493.2,...,0.220677,0.0,10.2,20.6,POINT (76000 2401000),168,Faible,1.0,29,347.199910
4,1958-08-01,760,24090,0.0,102.4,15.958065,3.764516,10.168677,103106.1,31489.5,...,0.217355,0.0,10.2,20.9,POINT (76000 2409000),135,Faible,1.0,29,232.342152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982859,2025-10-01,11960,17050,0.0,44.5,18.122581,2.538710,8.597774,91740.2,33351.6,...,0.190774,0.0,12.5,25.8,POINT (1196000 1705000),1180349,Faible,1.0,202,0.000000
7982860,2025-10-01,11960,17130,0.0,27.8,16.987097,2.683871,7.945290,92372.0,33203.6,...,0.194065,0.0,9.3,25.8,POINT (1196000 1713000),1180449,Moyen,2.0,202,0.000000
7982861,2025-10-01,11960,17210,0.0,27.8,16.967742,2.683871,7.937194,92353.8,33201.1,...,0.186806,0.0,9.3,25.8,POINT (1196000 1721000),1180520,Faible,1.0,202,0.000000
7982862,2025-10-01,11960,17290,0.0,27.8,16.967742,2.683871,7.937194,92353.8,33201.1,...,0.204161,0.0,9.3,25.8,POINT (1196000 1729000),1180530,Faible,1.0,202,620.374701
7982863,2025-10-01,11960,17450,0.0,27.7,17.100000,2.700000,7.990484,92475.1,33216.9,...,0.205387,0.0,9.5,25.8,POINT (1196000 1745000),1180495,Faible,1.0,202,3008.945185